spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: password
    
server:
  port: 9002


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
