spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: password

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
